iNaviUser/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include("iUser.urls", namespace="user")),
    url(r'^avatar/', include("upload_avatar.urls", namespace="avatar")),
    url(r'^/?', include("index.urls", namespace="index")),
]

iUrl/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

iUser/urls.py
# encoding: utf8
"""iNaviUser URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from views import main, login, register, logout, page_info, drop_user, update_bio, \
    update_skills, update_interests, update_figure, update_figure

from views_topic import show_topic, show_topics, update_topic, delete_topic, add_topic
from views_api import api_get_cate_topics, api_get_head
from views_url import add_url, show_urls, update_url, delete_url, upload_bookmark, collect, suggest
from views_note import add_note, show_note

urlpatterns = [
    url(r'^login/?$', login, name="login"),
    url(r'^register/?$', register, name="register"),
    url(r'^logout/?$', logout, name="logout"),
    url(r'^suggest/?$', suggest, name="suggest"),
    url(r'^(?P<username>\w+)/?$', main, name="main"),
    url(r'^(?P<username>\w+)/info/?$', page_info, name="info"),
    url(r'^(?P<username>\w+)/delete/?$', drop_user, name="delete"),
    url(r'^(?P<username>\w+)/update_bio/?$', update_bio, name="update_bio"),
    url(r'^(?P<username>\w+)/update_skills/?$', update_skills, name="update_skills"),
    url(r'^(?P<username>\w+)/update_interests/?$', update_interests, name="update_interests"),
    # url(r'^(?P<username>\w+)/update_figure/?$', update_figure, name="update_figure"),
    url(r'^(?P<username>\w+)/upload_avatar/?$', update_figure, name="update_avatar"),

    url(r'^(?P<username>\w+)/topic/(?P<topic_id>\d+)/?$', show_topic, name="show_topic"),
    # 这个地方用 show_topics 来跳转,防止每次都要取出用户的root_id
    url(r'^(?P<username>\w+)/topics/?$', show_topics, name="show_topics"),
    url(r'^(?P<username>\w+)/add_topic/?$', add_topic, name="add_topic"),
    url(r'^(?P<username>\w+)/update_topic/(?P<topic_id>\d+)/?$', update_topic, name="update_topic"),
    url(r'^(?P<username>\w+)/delete_topic/(?P<topic_id>\d+)/?$', delete_topic, name="delete_topic"),

    # urls
    url(r'^(?P<username>\w+)/add_url/?$', add_url, name="add_url"),
    url(r'^(?P<username>\w+)/update_url/(?P<user_url_id>\d+)/?$', update_url, name="update_url"),
    url(r'^(?P<username>\w+)/delete_url/(?P<user_url_id>\d+)/?$', delete_url, name="delete_url"),
    url(r'^(?P<username>\w+)/latest/?$', show_urls, name="latest"),
    url(r'^(?P<username>\w+)/bookmark/?$', upload_bookmark, name="upload_bookmark"),
    url(r'^(?P<username>\w+)/collect/?$', collect, name="collect"),

    url(r'^(?P<username>\w+)/add_note/?$', add_note, name="add_note"),
    url(r'^(?P<username>\w+)/show_note/?$', show_note, name="show_note"),

    # apis
    url(r"api/get_cate_topics/?", api_get_cate_topics, name="get_cate_topics"),
    url(r"api/api_get_head/?", api_get_head, name="api_get_head")
]

upload_avatar/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url


from . import views

urlpatterns = patterns('',
    url(r'^uploadavatar_upload/?$', views.upload_avatar, name="uploadavatar_upload"),
    url(r'^uploadavatar_crop/?$', views.crop_avatar, name="uploadavatar_crop"),
)

upload_avatar/models.py
# -*- coding: utf-8 -*-
import os

from django.db import models
from django.db.models.signals import post_delete


from .app_settings import (
    UPLOAD_AVATAR_UPLOAD_ROOT,
    UPLOAD_AVATAR_AVATAR_ROOT,
    UPLOAD_AVATAR_URL_PREFIX_CROPPED,
    UPLOAD_AVATAR_SAVE_FORMAT,
    UPLOAD_AVATAR_DEFAULT_SIZE,
)


class UploadAvatarMixIn(object):
    """user MUST define self.get_uid(), and self.get_avatar_name() method for using this mixin
    self.get_uid() return the current user's uid,
    self.get_avatar_name() return avatar name
    """
    
    def get_uploaded_image_name(self):
        try:
            return UploadedImage.objects.only('image').get(username=self.get_uid())
        except UploadedImage.DoesNotExist:
            return None
        
    def get_uploaded_image_path(self):
        name = self.get_uploaded_image_name()
        if not name:
            return name
        
        full_path = os.path.join(UPLOAD_AVATAR_UPLOAD_ROOT, name)
        if not os.path.exists(full_path):
            # delete from UploadedImage ??
            return None
        return full_path
    
    
    def build_avatar_name(self, name, size):
        return '%s-%d.%s' % (name, size, UPLOAD_AVATAR_SAVE_FORMAT)
    
    def get_avatar_path(self, size=UPLOAD_AVATAR_DEFAULT_SIZE):
        full_path = os.path.join(UPLOAD_AVATAR_AVATAR_ROOT, self.get_avatar_name(size))
        if not os.path.exists(full_path):
            return None
        return full_path
    
    def get_avatar_url(self, size=UPLOAD_AVATAR_DEFAULT_SIZE):
        return UPLOAD_AVATAR_URL_PREFIX_CROPPED + self.get_avatar_name(size)
    

class UploadedImage(models.Model):
    # uid = models.IntegerField(unique=True)
    username = models.CharField(unique=True, max_length=255, primary_key=True)
    image = models.CharField(max_length=255)
    upload_date = models.DateTimeField(auto_now_add=True)
    
    def get_image_path(self):
        path = os.path.join(UPLOAD_AVATAR_UPLOAD_ROOT, self.image)
        if not os.path.exists(path):
            return None
        return path


def _delete_avatar_on_disk(sender, instance, *args, **kwargs):
    path = instance.get_image_path()
    if path:
        try:
            os.unlink(path)
        except OSError:
            pass
    
    
post_delete.connect(_delete_avatar_on_disk, sender=UploadedImage)

iUser/views.py
# encoding:utf8
# Create your views here.
import os

from django.shortcuts import render, render_to_response, get_object_or_404, RequestContext
from django.utils import timezone
from django.http import HttpResponse, HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
# from django.views.decorators.csrf import csrf_protect
from django.contrib.auth.models import User
from django.contrib import auth
from iUser.models import user_info_api
from utils.tag_handler import TagHandler
from iUserTopic.models import topic_api
from models_url import user_url_api
from utils.pages import wrap_pages

def register(request):
    cur_time = timezone.now()
    register_template = "iUser/register.html"

    if request.user.is_authenticated():
        jump_template = "iUser/jump.html"
        return render(request, jump_template, {"msg": "You have already login!"})

    # user_form = UserForm(instance=User())
    errors = []
    if request.method == "POST":
        username = request.POST.get('username', '')
        password1 = request.POST.get('password1', '')
        password2 = request.POST.get("password2", '')
        email = request.POST.get("email", "")

        # user_form.username = username
        # user_form.password1 = password1
        # user_form.password2 = password2
        # user_form.email = email

        if password1 != password2:
            errors.append("password are not matched")
            return render_to_response(register_template,
                {'errors': errors})
        password = password1

        is_username_exist = User.objects.filter(username=username)
        if len(is_username_exist) > 0:
            errors.append("User already exists")
            return render(request, register_template, {'errors': errors})
        # create user
        User.objects.create_user(username=username, password=password, email=email)
        # init environment
        init_env(username)
        # authenticate user
        # user = auth.authenticate(username=username, password=password)

        return HttpResponseRedirect(reverse("user:login"))
    else:
        return render(request, register_template, {"errors": errors})


def init_env(username):
    user_info_api.create_user(username)
    topic_api.init(username)


def login(request):
    login_template = "iUser/login.html"
    errors = []
    if request.user.is_authenticated():
        jump_template = "iUser/jump.html"
        return render(request, jump_template, {"msg": "You have already login!"})
    # lazy way to avoid inputting username and password each time
    # username = request.COOKIES.get('username', '')
    # password = request.COOKIES.get('password', '')
    # user = auth.authenticate(username=username, password=password)
    # if user and user.is_active:
    #     auth.login(request, user)
    #     return HttpResponseRedirect(reverse("iUser:home"))
    ###############

    if request.method == "POST":
        username = request.POST.get("username", "")
        password = request.POST.get("password", "")
        user = auth.authenticate(username=username, password=password)
        if user and user.is_active:
            auth.login(request, user)
            response = HttpResponseRedirect(reverse("user:main", args=(username,)))
            response.set_cookie("username", username)
            return response

        errors.append("Username and password doesn't match")
    return render(request, login_template, {"form": request.POST, "errors": errors})


def logout(request):
    logout_template = "iUser/jump.html"
    if request.user.is_authenticated():
        auth.logout(request)
    next_page = {"url": reverse("index:index"), "name":"主页"}
    response = render(request, logout_template, {"next": next_page, "msg":"成功退出"})
    response.delete_cookie('username', path='/')
    # response.delete_cookie('password', path='/')
    return response


def page_info(request, username):
    template_file = "iUser/user_info.html"
    user_info = user_info_api.get_info(username)
    return render(request, template_file, {"user_info": user_info, "id": id})


def drop_user(request, username):
    jump_template = "iUser/jump.html"
    msg = ""
    # username = request.GET.get("username", "")
    user_obj = get_object_or_404(User, username=username)
    user_info_api.drop_user(username)
    topic_api.delete_user(username)

    next_page = {"url": reverse("index:index"), "name":"主页"}
    response = render(request, jump_template, {"next": next_page, "msg":msg})
    return response


from user_tools import get_user_info
# 登录用户的首页视图, 包含了导航\收藏等信息,不是index
def main(request, username):
    auth = False
    if request.user.is_authenticated():
        user_info = get_user_info(request)
        login_username = user_info['username']
        if login_username == username:
            auth = True
    if not auth:
        # 输出用户信息
        return HttpResponseRedirect(reverse("user:info", args=(username,)))

    site_id = topic_api.get_site_id(username)
    site_tree = user_url_api.get_topic_total_info(username, site_id)
    user_info = user_info_api.get_info(username)

    # 最近收藏
    user_recent_urls = user_url_api.get_recent_urls(username, size=10, page=1)
    template_file = "iUser/index.html"

    return render(request, template_file, {"user_info": user_info, "id": id,
                                           "site_tree": site_tree, "user_recent_urls":user_recent_urls})


# def update_figure(request, username):
#     if not request.user.is_authenticated():
#         return HttpResponseRedirect(reverse("user:login"))
#
#     user = request.user
#     username = user.username
#     if request.method == "POST":
#         new_bio = request.POST.get("bio", "")
#         user_info_api.update_bio(username, new_bio)
#         return HttpResponseRedirect(reverse("user:info", args=(username, )))
#     template_file = "iUser/update_figure.html"
#     user_info = user_info_api.get_info(username)
#     return render(request, template_file, {"user_info": user_info})


def update_bio(request, username):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse("user:login"))

    user = request.user
    username = user.username
    if request.method == "POST":
        new_bio = request.POST.get("bio", "")
        user_info_api.update_bio(username, new_bio)
        return HttpResponseRedirect(reverse("user:info", args=(username, )))
    template_file = "iUser/update_bio.html"
    user_info = user_info_api.get_info(username)
    return render(request, template_file, {"user_info": user_info})


def update_skills(request, username):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse("user:login"))

    user = request.user
    username = user.username
    if request.method == "POST":
        new_skills_str = request.POST.get("skills", "")
        new_skills = TagHandler.split(new_skills_str)
        user_info_api.update_skill(username, new_skills)
        return HttpResponseRedirect(reverse("user:info", args=(username, )))
    template_file = "iUser/update_skills.html"
    user_info = user_info_api.get_info(username)
    skills = ','.join([t['name'] for t in user_info['user_skills']])
    return render(request, template_file, {"user_info": user_info, "skills": skills})


def update_interests(request, username):
    if not request.user.is_authenticated():
        return HttpResponseRedirect(reverse("user:login"))

    user = request.user
    username = user.username
    if request.method == "POST":
        new_insterest_str = request.POST.get("interests", "")
        new_insterests = TagHandler.split(new_insterest_str)
        user_info_api.update_interest(username, new_insterests)
        return HttpResponseRedirect(reverse("user:info", args=(username, )))
    template_file = "iUser/update_interests.html"
    user_info = user_info_api.get_info(username)
    interests = ','.join([t['name'] for t in user_info['user_interests']])
    return render(request, template_file, {"user_info": user_info, "interests": interests})


from upload_avatar.app_settings import (
    UPLOAD_AVATAR_UPLOAD_ROOT,
    UPLOAD_AVATAR_AVATAR_ROOT,
    UPLOAD_AVATAR_RESIZE_SIZE,
)


from upload_avatar import get_uploadavatar_context
from .models import UserAvatar


#########################
# In production, you don't need this,
# static files should serve by web server, e.g. Nginx

def find_mimetype(filename):
    """In production, you don't need this,
    Static files should serve by web server, e.g. Nginx.
    """
    if filename.endswith(('.jpg', '.jpep')):
        return 'image/jpeg'
    if filename.endswith('.png'):
        return 'image/png'
    if filename.endswith('.gif'):
        return 'image/gif'
    return 'application/octet-stream'


def get_upload_images(request, filename):
    mimetype = find_mimetype(filename)
    with open(os.path.join(UPLOAD_AVATAR_UPLOAD_ROOT, filename), 'r') as f:
        #return HttpResponse(f.read(), mimetype=mimetype)
        return HttpResponse(f.read(), content_type=mimetype)


def get_avatar(request, filename):
    mimetype = find_mimetype(filename)
    with open(os.path.join(UPLOAD_AVATAR_AVATAR_ROOT, filename), 'r') as f:
        #return HttpResponse(f.read(), mimetype=mimetype)
        return HttpResponse(f.read(), content_type=mimetype)

# print "got here 11111>>>>>>>>>>>>>>>"
@login_required(login_url="/user/login/")
def update_figure(request, username):
    return render_to_response(
        'iUser/upload_avatar.html',
        get_uploadavatar_context(),
        context_instance=RequestContext(request)
    )

iUser/templates/iUser/add_topic.html
{% extends 'base_user.html' %}

{% block main %}

  <div class="container center-block">
    <div class="vertical-center col-xs-10 col-sm-10">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
            添加分类主题
          </h3>
        </div>
        <div class="panel-body">

          <form class="form-horizontal" action="{% url 'user:add_topic' user.username %}" method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="name" class="col-xs-4 col-sm-2 control-label">分类名</label>
              <div class="col-xs-12 col-sm-8 col-md-6">
                <input type="text" class="form-control" id="name" name="name" placeholder="分类名">
              </div>
            </div>
            <div class="form-group">
              <label for="topics" class="col-xs-4 col-sm-2 control-label required">父分类</label>
              <div class="col-xs-12 col-sm-8 col-md-6">
                <select id="topics" name="topic_id">
                   {{ user_topics|safe }}
                </select>
              </div>
            </div>
            <div class="form-group">
              <label for="info" class="col-xs- col-sm-2 control-label required">标签</label>
              <div class="col-xs-12 col-sm-8 col-md-6">
                <textarea id="info" style="width: 100%" name="info" placeholder="填写说明或备注"></textarea>
              </div>
            </div>
            <div class="form-group">
              <label for="score" class="col-xs-4 col-sm-2 control-label required">重要性</label>
              <div class="col-xs-4">
                <input type="number" class="form-control" id="score" name="score" value="5">
              </div>
            </div>
            <div class="form-group">
              <div class="col-xs-12 text-center">
                <button type="submit" class="btn btn-default">提 交</button>
              </div>
            </div>
          </form>
        </div>
        {% if errors %}
          {% for error in errors %}
            <div><p class="bg-danger">{{ error }}</p></div>

          {% endfor %}
        {% endif %}
      </div>

    </div>
  </div>

{% endblock %}

iUser/templates/iUser/add_url.html
{% extends 'base_user.html' %}

{% block main %}

  <script>
    function getHead() {
      var f = document.forms['form_add_url']
      var url = f.url.value;
      $.ajax({
        url:"{% url 'user:api_get_head' %}"+"?url="+url,
        dataType: "JSON",
        success: function(resp){
          var code = resp.code;
          var msg = resp.msg;
          if(code!=0){
            alert("error:"+msg)
          }else{
            var d = resp.data;
            f.name.value = d;
          }
        },
        fail: function(resp){
          alert("unknown error happens");
        }
      })
    }
  </script>
  <div class="container center-block">
    <div class="vertical-center col-xs-12 col-sm-10">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
            添加地址
          </h3>
        </div>
        <div class="panel-body">

          <form name="form_add_url" class="form-horizontal" action="{% url 'user:add_url' user.username %}"
                method="post">
            {% csrf_token %}
            <div class="form-group">
              <label for="url" class="col-xs-6 col-sm-2 control-label required">地址</label>
              <div class="col-xs-12 col-sm-10">
                <input type="url" class="form-control" id="url" name="url" placeholder="URL地址">
              </div>
            </div>
            <div class="form-group">
              <label for="name" class="col-xs-6 col-sm-2 control-label">名称</label>
              <div class="col-xs-12 col-sm-7">
                <input type="text" class="form-control" id="name" name="name" placeholder="自定义名字, 或者自动为URL TITLE">
              </div>
              <div class="col-xs-6 col-sm-3"><a class="btn" onclick="getHead()">自动获取地址名称</a></div>
            </div>
            <div class="form-group">
              <label for="tags" class="col-xs-6 col-sm-2 control-label required">标签</label>
              <div class="col-xs-12 col-sm-10">
                <input type="text" class="form-control" id="tags" name="tags" placeholder="用逗号隔开">
              </div>
            </div>
            <div class="form-group">
              <label for="topics" class="col-xs-6 col-sm-2 control-label required">分类</label>
              <div class="col-xs-12 col-sm-10">
                <select id="topics" name="topic_id">
                  {{ user_topics|safe }}
                </select>
              </div>
            </div>

            <div class="form-group">
              <label for="score" class="col-xs-7 col-sm-2 control-label required">重要性</label>
              <div class="col-xs-6">
                <input type="number" class="form-control" id="score" name="score" value="5">
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-offset-4 col-sm-10">
                <button type="submit" class="btn btn-default">提 交</button>
              </div>
            </div>
          </form>
        </div>
        {% if errors %}
          {% for error in errors %}
            <div><p class="bg-danger">{{ error }}</p></div>

          {% endfor %}
        {% endif %}
      </div>

    </div>
  </div>

{% endblock %}

iUser/templates/iUser/login.html
{% extends 'base.html' %}

{% block content %}

  <div class="container center-block">
    <div class="vertical-center col-xs-12 col-sm-6">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
            登录
          </h3>
        </div>
        <div class="panel-body">

          <form class="form-horizontal" method="post" action="{% url 'user:login' %}" style="">
            {% csrf_token %}
            <div class="form-group">
              <label for="username" class="col-xs-8 col-sm-4 control-label">用户名或Email</label>
              <div class="col-xs-12 col-sm-8">
                <input type="text" class="form-control" id="username" name="username" placeholder="用户名或Email">
              </div>
            </div>
            <div class="form-group">
              <label for="password" class="col-xs-8 col-sm-4 control-label">密 码</label>
              <div class="col-xs-12 col-sm-8">
                <input type="password" class="form-control" id="password" name="password" placeholder="Password">
              </div>
            </div>
            <div class="form-group">
              <div class="col-xs-10">
                <div class="checkbox">
                  <label>
                    <input type="checkbox"> Remember me
                  </label>
                </div>
              </div>
            </div>
            <div class="form-group">
              <div class="col-xs-12">
                <button type="submit" class="btn btn-default">登 录</button> 没有账号?
                <a type="btn" class="btn btn-default" href="{% url "user:register" %}">注 册</a>
              </div>
            </div>
          </form>
        </div>
        {% if errors %}
          {% for error in errors %}
            <div><p class="bg-danger">{{ error }}</p></div>

          {% endfor %}
        {% endif %}
      </div>

    </div>
  </div>
{% endblock %}

iUser/templates/iUser/register.html
{% extends 'base.html' %}

{% block content %}

  <div>
    {% if errors %}
      {% for error in errors %}
        <p>{{ error }}</p>
      {% endfor %}
    {% endif %}
  </div>

  <div class="container center-block">
    <div class="vertical-center col-xs-12 col-sm-10">
      <div class="panel panel-primary">
        <div class="panel-heading">
          <h3 class="panel-title">
            注册
          </h3>
        </div>
        <div class="panel-body">

          <form class="form-horizontal" action="{% url 'user:register' %}" method='post'>
            {% csrf_token %}
            <div class="form-group">
              <label for="username" class="col-xs-6 col-sm-2 control-label">用户名</label>
              <div class="col-sm-8">
                <input type="text" class="form-control" id="username" name="username" placeholder="用户名">
              </div>
            </div>
            <div class="form-group">
              <label for="email" class="col-xs-6 col-sm-2 control-label">Email</label>
              <div class="col-sm-8">
                <input type="email" class="form-control" id="email" name="email" placeholder="Email">
              </div>
            </div>
            <div class="form-group">
              <label for="password1" class="col-xs-6 col-sm-2 control-label">密码</label>
              <div class="col-sm-8">
                <input type="password" class="form-control" id="password1" name="password1" placeholder="Password">
              </div>
            </div>
            <div class="form-group">
              <label for="password2" class="col-xs-6 col-sm-2 control-label">确认密码</label>
              <div class="col-sm-8">
                <input type="password" class="form-control" id="password2" name="password2" placeholder="Password">
              </div>
            </div>
            <div class="form-group">
              <div class="col-sm-12">
                <button type="submit" class="btn btn-default">注 册</button> 已有账号? <a type="button" class="btn btn-default" href="{% url 'user:login' %}">登 录</a>

              </div>
            </div>
          </form>

        </div>
        {% if errors %}
          {% for error in errors %}
            <div><p class="bg-danger">{{ error }}</p></div>

          {% endfor %}
        {% endif %}
      </div>

    </div>
  </div>

{% endblock %}

iUser/templates/iUser/show_topic.html
{% extends 'base_user.html' %}

{% block main %}

  <div>
    <h3><a href="{% url 'user:show_topics' user.username %}">收藏目录:</a>  </h3>
    <h4>
      {% for node in topic_path %}

      <a href="{% url 'user:show_topic' user.username node.child_id %}">{{ node.name }}</a> >>
    {% endfor %}
    </h4>
  </div>

  <div class="directory">
    <ul class="list-group">
    {% for url in topic_urls %}
      <li class="list-group-item">
      <a href="{{ url.url_info.url }}">{% if url.name %}{{ url.name }}{% else %}{{ url.url_info.url }}{% endif %}</a>
  <span class="small">{{ url.last_update_time }}</span>
        <div style="display:inline-block; float: right;">
            <a href="{% url 'user:update_url' user.username url.id %}">修改</a>
            <a href="{% url 'user:delete_url' user.username url.id %}">删除</a>
        </div>
      </li>
    {% endfor %}
      {% for topic in sub_topics %}
        <li class="list-group-item folder">
          <a href="{% url 'user:show_topic' user.username topic.child_id %}">{{ topic.name }}<a>
          <div style="display:inline-block; float: right;">
            <a href="{% url 'user:update_topic' user.username topic.child_id %}">修改</a>
            <a href="{% url 'user:delete_topic' user.username topic.child_id %}">删除</a>
          </div>
        </li>
      {% endfor %}
    </ul>
  </div>

{% endblock %}

iUser/templates/iUser/show_topics.html
{% extends 'base_user.html' %}

{% block main %}

  <div>
    <h4>
      收藏目录 >
    </h4>
    <a class="btn btn-primary" href="{% url 'user:add_topic' user.username %}">添加分类</a>
  </div>

  <table id="topic-table">
    <tbody>
    {{ topics|safe }}
    </tbody>
  </table>

      <script>

      $("#topic-table").treetable({expandable: true, clickableNodeNames: false, indent: 15, initialState: "expanded"});
      {#    $("#topic-table").treetable({expandable: true, indent: 15, initialState: "expanded"});#}

      // Highlight selected row
      $("#topic-table tbody").on("mousedown", "tr", function () {
        $(".selected").not(this).removeClass("selected");
        $(this).toggleClass("selected");
      });

      // Drag & Drop Example Code
      $("#topic-table .file, #topic-table .folder").draggable({
        helper: "clone",
        opacity: .75,
        refreshPositions: true, // Performance?
        revert: "invalid",
        revertDuration: 300,
        scroll: true
      });

      $("#topic-table .folder").each(function () {
        $(this).parents("#topic-table tr").droppable({
          accept: ".file, .folder",
          drop: function (e, ui) {
            var droppedEl = ui.draggable.parents("tr");
            $("#topic-table").treetable("move", droppedEl.data("ttId"), $(this).data("ttId"));
          },
          hoverClass: "accept",
          over: function (e, ui) {
            var droppedEl = ui.draggable.parents("tr");
            if (this != droppedEl[0] && !$(this).is(".expanded")) {
              $("#topic-table").treetable("expandNode", $(this).data("ttId"));
            }
          }
        });
      });

      $("form#reveal").submit(function () {
        var nodeId = $("#revealNodeId").val()

        try {
          $("#topic-table").treetable("reveal", nodeId);
        }
        catch (error) {
          alert(error.message);
        }

        return false;
      });

  </script>
{% endblock %}

iUser/templates/iUser/user_info.html
{% extends 'base_user.html' %}

{% block main %}

  <script>
    // 针对首页的来打开相应的url
    function openItem(url) {
      if (url.length > 5) {
        window.open(url, "_blank")
      }
    }
  </script>

  <div class="jumbotron" id="user-info-header">
      <img class="img-circle" src="{{ user_info.user_avatar }}" width="100px">
      <h2>{{ user_info.username }}</h2>
      <p class="bio">{{ user_info.bio }}</p>
      <p class="tags">擅长:{% for sk in user_info.user_skills %}#{{ sk.name }} {% endfor %}</p>
      <p class="tags">关注:{% for int in user_info.user_interests %}#{{ int.name }} {% endfor %}</p>
  </div>

  <div class="container">
    <a href="{% url 'user:update_avatar' user.username %}">修改头像</a>
    <a href="{% url 'user:update_bio' user.username %}">修改简介</a>
    <a href="{% url 'user:update_skills' user.username %}">修改技能</a>
    <a href="{% url 'user:update_interests' user.username %}">修改关注领域</a>
  </div>

{% endblock %}