iNaviUser/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include("iUser.urls", namespace="user")),
    url(r'^avatar/', include("upload_avatar.urls", namespace="avatar")),
    url(r'^/?', include("index.urls", namespace="index")),
]

iUrl/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

iUser/urls.py
# encoding: utf8
"""iNaviUser URL Configuration

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/1.9/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  url(r'^$', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  url(r'^$', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.conf.urls import url, include
    2. Add a URL to urlpatterns:  url(r'^blog/', include('blog.urls'))
"""
from django.conf.urls import url
from django.contrib import admin
from views import main, login, register, logout, page_info, drop_user, update_bio, \
    update_skills, update_interests, update_figure, update_figure

from views_topic import show_topic, show_topics, update_topic, delete_topic, add_topic
from views_api import api_get_cate_topics, api_get_head
from views_url import add_url, show_urls, update_url, delete_url, upload_bookmark, collect, suggest
from views_note import add_note, show_note

urlpatterns = [
    url(r'^login/?$', login, name="login"),
    url(r'^register/?$', register, name="register"),
    url(r'^logout/?$', logout, name="logout"),
    url(r'^suggest/?$', suggest, name="suggest"),
    url(r'^(?P<username>\w+)/?$', main, name="main"),
    url(r'^(?P<username>\w+)/info/?$', page_info, name="info"),
    url(r'^(?P<username>\w+)/delete/?$', drop_user, name="delete"),
    url(r'^(?P<username>\w+)/update_bio/?$', update_bio, name="update_bio"),
    url(r'^(?P<username>\w+)/update_skills/?$', update_skills, name="update_skills"),
    url(r'^(?P<username>\w+)/update_interests/?$', update_interests, name="update_interests"),
    # url(r'^(?P<username>\w+)/update_figure/?$', update_figure, name="update_figure"),
    url(r'^(?P<username>\w+)/upload_avatar/?$', update_figure, name="update_avatar"),

    url(r'^(?P<username>\w+)/topic/(?P<topic_id>\d+)/?$', show_topic, name="show_topic"),
    # 这个地方用 show_topics 来跳转,防止每次都要取出用户的root_id
    url(r'^(?P<username>\w+)/topics/?$', show_topics, name="show_topics"),
    url(r'^(?P<username>\w+)/add_topic/?$', add_topic, name="add_topic"),
    url(r'^(?P<username>\w+)/update_topic/(?P<topic_id>\d+)/?$', update_topic, name="update_topic"),
    url(r'^(?P<username>\w+)/delete_topic/(?P<topic_id>\d+)/?$', delete_topic, name="delete_topic"),

    # urls
    url(r'^(?P<username>\w+)/add_url/?$', add_url, name="add_url"),
    url(r'^(?P<username>\w+)/update_url/(?P<user_url_id>\d+)/?$', update_url, name="update_url"),
    url(r'^(?P<username>\w+)/delete_url/(?P<user_url_id>\d+)/?$', delete_url, name="delete_url"),
    url(r'^(?P<username>\w+)/latest/?$', show_urls, name="latest"),
    url(r'^(?P<username>\w+)/bookmark/?$', upload_bookmark, name="upload_bookmark"),
    url(r'^(?P<username>\w+)/collect/?$', collect, name="collect"),

    url(r'^(?P<username>\w+)/add_note/?$', add_note, name="add_note"),
    url(r'^(?P<username>\w+)/show_note/?$', show_note, name="show_note"),

    # apis
    url(r"api/get_cate_topics/?", api_get_cate_topics, name="get_cate_topics"),
    url(r"api/api_get_head/?", api_get_head, name="api_get_head")
]

index/urls.py
from django.conf.urls import url
from django.contrib import admin
from views import get_index

urlpatterns = [
    url(r"^/?$", get_index, name="index"),
    # url(r'^(?P<username>\w+)/?$', get_user_index, name="user"),
]

templates/base.html
<!DOCTYPE html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
  <meta name="description" content="">
  <meta name="author" content="">
  {#    <link rel="icon" href="../../favicon.ico">#}

  <title>{% block site-name %}个性化导航{% endblock %}</title>

  <!-- Bootstrap core CSS -->
{#  <link href="//cdn.bootcss.com/bootstrap/4.0.0-alpha.3/css/bootstrap.min.css" rel="stylesheet">#}
    <link href="//cdn.bootcss.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

  <!-- Custom styles for this template -->

  {#  http://www.bootcdn.cn/jquery-treetable/#}
  <link rel="stylesheet" href="/static/css/screen.css" media="screen"/>
{#    <link rel="stylesheet" href="/static/css/jquery.treetable.css"/>#}
  <link href="//cdn.bootcss.com/jquery-treetable/3.2.0/css/jquery.treetable.min.css" rel="stylesheet">
{#  <link href="//cdn.bootcss.com/jquery-treetable/3.2.0/css/jquery.treetable.theme.default.css" rel="stylesheet">#}
    <link rel="stylesheet" href="/static/css/jquery.treetable.theme.default.css"/>

  <link href="/static/css/dashboard.css" rel="stylesheet">
  <link href="/static/css/simple-sidebar.css" rel="stylesheet">
  <link href="/static/css/app.css" rel="stylesheet">

<script src="//cdn.bootcss.com/jquery/3.1.0/jquery.min.js"></script>
{#  <script src="/static/js/jquery.min.js"></script>#}
  <script src="/static/js/jquery-ui.min.js"></script>

  <script src="//cdn.bootcss.com/bootstrap/4.0.0-alpha.3/js/bootstrap.min.js"></script>
{#  <script src="/static/js/bootstrap.min.js"></script>#}

  <script src="//cdn.bootcss.com/jquery-treetable/3.2.0/jquery.treetable.min.js"></script>
{#    <script src="/static/js/jquery.treetable.js"></script>#}

  <script src="/static/js/app.js"></script>
  <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
  <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
  {#    <script src="../../assets/js/ie-emulation-modes-warning.js"></script>#}

  <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<!-- Static navbar -->
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
        <span></span>
        <span class="sr-only"><a href="{% url 'index:index' %}">Webook</a></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'index:index' %}">Webook</a>
    </div>

    <div id="navbar" class="navbar-collapse collapse" style="z-index: 1000">
      <ul class="nav navbar-nav navbar-right dropdown">

        {% if user.is_authenticated %}

          {% ifequal user.username 'admin' %}
            <li role="presentation" class="dropdown">
              <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
                操作 <span class="caret"></span>
              </a>
              <ul class="dropdown-menu">
                <li role="presentation">
                  <a role="menuitem" tabindex="-1" href="" data-toggle="modal" data-target="#drop_user_modal">删除用户</a>
                </li>
              </ul>
            </li>
          {% endifequal %}
          <li class="active"><a class="btn btn-default" href="{% url 'user:add_url' user.username %}">添加链接</a></li>
          <li class="active"><a class="btn btn-default" href="{% url 'user:add_note' user.username %}">添加笔记</a></li>
{#          <li><a href="">消息T</a></li>#}
          <li><a href="">提醒T</a></li>
          <li role="presentation" class="dropdown">
            <a class="dropdown-toggle" data-toggle="dropdown" data-hover="dropdown">
              {{ user.username }} <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li role="presentation" class="divider">操作</li>
              <li role="presentation">
                <a role="menuitem" tabindex="-1" href="">我的名片(todo</a>
              </li>
              <li role="presentation">
                <a role="menuitem" tabindex="-1" href="">个人设置(todo)</a>
              </li>
              <li role="presentation" class="divider"></li>
              <li role="presentation">
                <a role="menuitem" tabindex="-1" href="{% url 'user:logout' %}">退出</a>
              </li>
            </ul>
          </li>

        {% else %}
          <li><a href="{% url 'user:login' %}">登录</a></li>
          <li><a href="{% url 'user:register' %}">注册</a></li>
        {% endif %}
      </ul>

    </div>
  </div>
</nav>

{% block content %}

  user: {{ user }}
  {% if user.is_authenticated %}
    <p>Welcome, {{ user.username }}. Thanks for logging in.</p>
  {% else %}
    <p>Welcome, new user. Please log in.</p>
  {% endif %}


{% endblock %}


<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
{#    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>#}
</body>
</html>

templates/base_user.html
{% extends 'base.html' %}

{% block content %}

  <div id="main-wrapper">
    <div id="sidebar-wrapper">
      {% block sidebar %}
        <div class="nav nav-sidebar sidebar-nav">
          <div class="panel">

            {#              登录信息#}
            {% if user.is_authenticated %}
              <div class="user-logo">
                <img class="img-circle" src="{{ user_info.user_avatar }}" width="80px">
                <h3>{{ user_info.username }}</h3>
                <p>{{ user_info.bio }}</p>
              </div>
            {% else %}
              <div class="panel-heading">
                <h3 class="panel-title text-center">
                  登录
                </h3>
              </div>
              <div class="panel-body">

                <form class="form-horizontal" method="post" action="{% url 'user:login' %}" style="">
                  {% csrf_token %}
                  <div class="form-group">
                    <div class="col-xs-12">
                      <input type="text" class="form-control" id="username" name="username" placeholder="用户名或Email">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-xs-12">
                      <input type="password" class="form-control" id="password" name="password"
                             placeholder="Password">
                    </div>
                  </div>
                  <div class="form-group">
                    <div class="col-xs-12">
                      <button type="submit" class="btn btn-primary col-xs-12">登 录</button>
                      没有账号?
                      <a type="btn" class="btn btn-default" href="{% url "user:register" %}">注 册</a>
                    </div>
                  </div>
                </form>
              </div>
              {% if errors %}
                {% for error in errors %}
                  <div><p class="bg-danger">{{ error }}</p></div>
                {% endfor %}
              {% endif %}

            {% endif %}
          </div>

          {#          菜单信息#}
          {% if user.is_authenticated %}
            <ul class="nav nav-sidebar">
              <li><a href="{% url 'user:main' user.username %}">我的主页</a></li>
              <li><a href="{% url 'user:latest' user.username %}">最新收藏</a></li>
              <li><a href="{% url 'user:show_topics' user.username %}">收藏目录</a>

              </li>
              <li><a href="{% url 'user:show_note' user.username %}">我的笔记</a></li>
              <li><a href="">我的知识夹(todo)</a></li>
              <li><a href="">我的关注(todo)</a></li>
              <li><a href="{% url 'user:info' user.username %}">个人信息</a></li>
            </ul>
            <hr>
            <ul class="nav nav-sidebar">
              <li><a href="{% url 'user:upload_bookmark' user.username %}">导入收藏夹</a></li>
              <li><a href="{% url 'user:collect' user.username %}">收集工具(todo)</a></li>
              <li><a href="{% url 'user:suggest' %}">建议&反馈</a></li>
              <li style="line-height: 30px"><span>上下知识@2006</span></li>
            </ul>
          {% else %}

            <ul class="nav nav-sidebar">
              <li><a href="">WELCOME</a></li>
              <li><a href="">首页</a></li>
              <li><a href="">最新用户(todo)</a></li>
              <li><a href="">功能说明(todo)</a></li>
            </ul>
          {% endif %}

        </div>
      {% endblock %}
    </div>

    <div id="page-content-wrapper">
      <a href="#menu-toggle" class="btn btn-default glyphicon glyphicon-th" id="menu-toggle"></a>
      {% block main %}
        <h2>The base User template</h2>
      {% endblock %}
    </div>
  </div>
  <script>
    $("#menu-toggle").click(function (e) {
      e.preventDefault();
      $("#main-wrapper").toggleClass("toggled");
    });
  </script>

{% endblock %}