iNaviUser/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^user/', include("iUser.urls", namespace="user")),
    url(r'^avatar/', include("upload_avatar.urls", namespace="avatar")),
    url(r'^/?', include("index.urls", namespace="index")),
]

iUrl/urls.py
from django.conf.urls import url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
]

upload_avatar/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, url


from . import views

urlpatterns = patterns('',
    url(r'^uploadavatar_upload/?$', views.upload_avatar, name="uploadavatar_upload"),
    url(r'^uploadavatar_crop/?$', views.crop_avatar, name="uploadavatar_crop"),
)

upload_avatar/models.py
# -*- coding: utf-8 -*-
import os

from django.db import models
from django.db.models.signals import post_delete


from .app_settings import (
    UPLOAD_AVATAR_UPLOAD_ROOT,
    UPLOAD_AVATAR_AVATAR_ROOT,
    UPLOAD_AVATAR_URL_PREFIX_CROPPED,
    UPLOAD_AVATAR_SAVE_FORMAT,
    UPLOAD_AVATAR_DEFAULT_SIZE,
)


class UploadAvatarMixIn(object):
    """user MUST define self.get_uid(), and self.get_avatar_name() method for using this mixin
    self.get_uid() return the current user's uid,
    self.get_avatar_name() return avatar name
    """
    
    def get_uploaded_image_name(self):
        try:
            return UploadedImage.objects.only('image').get(username=self.get_uid())
        except UploadedImage.DoesNotExist:
            return None
        
    def get_uploaded_image_path(self):
        name = self.get_uploaded_image_name()
        if not name:
            return name
        
        full_path = os.path.join(UPLOAD_AVATAR_UPLOAD_ROOT, name)
        if not os.path.exists(full_path):
            # delete from UploadedImage ??
            return None
        return full_path
    
    
    def build_avatar_name(self, name, size):
        return '%s-%d.%s' % (name, size, UPLOAD_AVATAR_SAVE_FORMAT)
    
    def get_avatar_path(self, size=UPLOAD_AVATAR_DEFAULT_SIZE):
        full_path = os.path.join(UPLOAD_AVATAR_AVATAR_ROOT, self.get_avatar_name(size))
        if not os.path.exists(full_path):
            return None
        return full_path
    
    def get_avatar_url(self, size=UPLOAD_AVATAR_DEFAULT_SIZE):
        return UPLOAD_AVATAR_URL_PREFIX_CROPPED + self.get_avatar_name(size)
    

class UploadedImage(models.Model):
    # uid = models.IntegerField(unique=True)
    username = models.CharField(unique=True, max_length=255, primary_key=True)
    image = models.CharField(max_length=255)
    upload_date = models.DateTimeField(auto_now_add=True)
    
    def get_image_path(self):
        path = os.path.join(UPLOAD_AVATAR_UPLOAD_ROOT, self.image)
        if not os.path.exists(path):
            return None
        return path


def _delete_avatar_on_disk(sender, instance, *args, **kwargs):
    path = instance.get_image_path()
    if path:
        try:
            os.unlink(path)
        except OSError:
            pass
    
    
post_delete.connect(_delete_avatar_on_disk, sender=UploadedImage)

upload_avatar/views.py
# -*- coding: utf-8 -*-

import os
import hashlib
import time
from functools import wraps

from PIL import Image

from django.http import HttpResponse
from django.utils.crypto import get_random_string

from .app_settings import (
    UPLOAD_AVATAR_TEST_FUNC as test_func,
    UPLOAD_AVATAR_GET_UID_FUNC as get_uid,
    UPLOAD_AVATAR_MAX_SIZE,
    UPLOAD_AVATAR_UPLOAD_ROOT,
    UPLOAD_AVATAR_AVATAR_ROOT,
    UPLOAD_AVATAR_URL_PREFIX_ORIGINAL,
    UPLOAD_AVATAR_RESIZE_SIZE,
    UPLOAD_AVATAR_SAVE_FORMAT,
    UPLOAD_AVATAR_SAVE_QUALITY,
    UPLOAD_AVATAR_DELETE_ORIGINAL_AFTER_CROP,
    
    UPLOAD_AVATAR_WEB_LAYOUT,
    UPLOAD_AVATAR_TEXT,
)


from .signals import avatar_crop_done
from .models import UploadedImage


border_size = UPLOAD_AVATAR_WEB_LAYOUT['crop_image_area_size']


class UploadAvatarError(Exception):
    pass


def protected(func):
    @wraps(func)
    def deco(request, *args, **kwargs):
        if not test_func(request):
            return HttpResponse(
                "<script>window.parent.upload_avatar_error('%s')</script>" % UPLOAD_AVATAR_TEXT['TEST_FUNC_NOT_PASSED']
            )
        try:
            return func(request, *args, **kwargs)
        except UploadAvatarError as e:
            return HttpResponse(
                "<script>window.parent.upload_avatar_error('%s')</script>" % e
            )
    return deco


@protected
def upload_avatar(request):
    try:
        uploaded_file = request.FILES['uploadavatarfile']
    except KeyError:
        raise UploadAvatarError(UPLOAD_AVATAR_TEXT['INVALID_IMAGE'])
    
    if uploaded_file.size > UPLOAD_AVATAR_MAX_SIZE:
        raise UploadAvatarError(UPLOAD_AVATAR_TEXT['TOO_LARGE'])
    
    name, ext = os.path.splitext(uploaded_file.name)
    new_name = hashlib.md5(
        '%s%f' % (get_random_string(), time.time())
    ).hexdigest()
    new_name = '%s%s' % (new_name, ext.lower())
    
    fpath = os.path.join(UPLOAD_AVATAR_UPLOAD_ROOT, new_name)
    
    with open(fpath, 'wb') as f:
        for c in uploaded_file.chunks(10240):
            f.write(c)
            
    try:
        Image.open(fpath)
    except IOError:
        try:
            os.unlink(fpath)
        except:
            pass
        raise UploadAvatarError(UPLOAD_AVATAR_TEXT['INVALID_IMAGE'])
        
    # uploaed image has been saved on disk, now save it's name in db
    if UploadedImage.objects.filter(username=get_uid(request)).exists():
        UploadedImage.objects.filter(username=get_uid(request)).update(image=new_name)
    else:
        UploadedImage.objects.create(username=get_uid(request), image=new_name)
        
    return HttpResponse(
        "<script>window.parent.upload_avatar_success('%s')</script>" % \
        (UPLOAD_AVATAR_URL_PREFIX_ORIGINAL + new_name)
    )


@protected
def crop_avatar(request):
    try:
        upim = UploadedImage.objects.get(username=get_uid(request))
    except UploadedImage.DoesNotExist:
        raise UploadAvatarError(UPLOAD_AVATAR_TEXT['NO_IMAGE'])
    
    image_orig = upim.get_image_path()
    if not image_orig:
        raise UploadAvatarError(UPLOAD_AVATAR_TEXT['NO_IMAGE'])
    
    try:
        x1 = int(float(request.POST['x1']))
        y1 = int(float(request.POST['y1']))
        x2 = int(float(request.POST['x2']))
        y2 = int(float(request.POST['y2']))
    except:
        raise UploadAvatarError(UPLOAD_AVATAR_TEXT['ERROR'])
    
    
    try:
        orig = Image.open(image_orig)
    except IOError:
        raise UploadAvatarError(UPLOAD_AVATAR_TEXT['NO_IMAGE'])
    
    orig_w, orig_h = orig.size
    if orig_w <= border_size and orig_h <= border_size:
        ratio = 1
    else:
        if orig_w > orig_h:
            ratio = float(orig_w) / border_size
        else:
            ratio = float(orig_h) / border_size
            
    box = [int(x * ratio) for x in [x1, y1, x2, y2]]
    avatar = orig.crop(box)
    avatar_name, _ = os.path.splitext(upim.image)
    
    def _resize(size):
        res = avatar.resize((size, size), Image.ANTIALIAS)
        res_name = '%s-%d.%s' % (avatar_name, size, UPLOAD_AVATAR_SAVE_FORMAT)
        res_path = os.path.join(UPLOAD_AVATAR_AVATAR_ROOT, res_name)
        res.save(res_path, UPLOAD_AVATAR_SAVE_FORMAT, quality=UPLOAD_AVATAR_SAVE_QUALITY)
        
    for size in UPLOAD_AVATAR_RESIZE_SIZE:
        _resize(size)
        
    avatar_crop_done.send(sender=None, username=get_uid(request), avatar_name=avatar_name)
    if UPLOAD_AVATAR_DELETE_ORIGINAL_AFTER_CROP:
        upim.delete()
        
    return HttpResponse(
        "<script>window.parent.crop_avatar_success('%s')</script>"  % UPLOAD_AVATAR_TEXT['SUCCESS']
    )

upload_avatar/templates/upload_avatar/upload_avatar.html
<div id="uploadAvatar">
    <link rel="stylesheet" href="/static/css/imgareaselect-default.css" type="text/css" />
    <script type="text/javascript" src="/static/js/jquery.imgareaselect.min.js"></script>
    
    <style type="text/css">
        #uploadAvatarBtnLayout {
            position: relative;
        }
        
        #uploadAvatarBtnLayout {
            overflow: hidden;
        }
        
        #uploadAvatarBtnLayout button {
            width: 100%;
            height: 100%;
        }
        
        #uploadAvatarInputFile {
            position: absolute;
            top: 0;
            left: -20px;
            font-size: 300%;
        }
        
        #uploadAvatarSelectArea {
            width: {{ crop_image_area_size }}px;
            height: {{ crop_image_area_size }}px;
            border: 1px solid #ddd;
            overflow: hidden;
            float: left;
        }
        
        #uploadAvatarPreviewArea {
            float: right;
        }
        
        {% for p in preview_areas %}
            #uploadAvatarPreviewArea{{ p.size }} {
                width: {{ p.size }}px;
                height: {{ p.size }}px;
                border: 1px solid #ddd;
                overflow: hidden;
            }
        {% endfor %}
    </style>
    
    <script type="text/javascript">
        $(function(){
            $('#uploadAvatarBtnLayout button').click(function(){
                return false;
            });
            
            var input_width = $('#uploadAvatarBtnLayout').width();
            var input_height = $('#uploadAvatarBtnLayout').height();
            
            $('#uploadAvatarInputFile').css({opacity: 0}).width(input_width + 50).height(input_height).change(function(){
                if($(this).val() == ''){return;}
                var $last_img = $('#uploadAvatarSelectArea img');
                if($last_img.length) {
                    var img_obj = $last_img.imgAreaSelect({instance: true});
                    img_obj.remove();
                }
                $('#uploadAvatarSelectArea').empty();
                $('#uploadAvatarPreviewArea div').empty();
                var p = new RegExp(/\.(jpg|jpeg|png|gif)$/);
                var fileanme = $(this).val().toLowerCase().replace(/^\s+|\s+$/g, '');
                if(!p.test(fileanme)){alert("{{ INVALID_IMAGE }}"); return;}
                $('#uploadAvatarForm').submit();
                $(this).val('');
                $('#uploadAvatarCropSubmit').removeAttr('disabled');
            });
            
            
            $('#uploadAvatarCropSubmit').click(function(){
                $(this).attr('disabled', 'disabled');
                var x1 = $('#uploadAvatarValueX1').val();
                var y1 = $('#uploadAvatarValueY1').val();
                var x2 = $('#uploadAvatarValueX2').val();
                var y2 = $('#uploadAvatarValueY2').val();
                if(x1 == "" || y1 == "" || x2 == "" ||y2 == "") {
                    $(this).removeAttr('disabled');
                    return false;
                }
                
                $('#uploadAvatarCropForm').submit();
                $('#uploadAvatarValueX1').val('');
                $('#uploadAvatarValueY1').val('');
                $('#uploadAvatarValueX2').val('');
                $('#uploadAvatarValueY2').val('');
                
                $(this).removeAttr('disabled');
                return false;
            });
        });
        
        function upload_avatar_error(error_msg) {
            alert(error_msg);
        };
        
        
        function upload_avatar_success(image_url) {
            $('#uploadAvatarSelectArea').empty();
            $('#uploadAvatarPreviewArea div').empty();
            $('#uploadAvatarPreviewArea div').append('<img />');
            $('#uploadAvatarPreviewArea div img').attr('src', image_url);
            
            $('#uploadAvatarSelectArea').append('<img />');
            $('#uploadAvatarSelectArea img').attr('src', image_url).load(function(){
                $(this).unbind('load');
                
                var img_width = $(this).width();
                var img_height = $(this).height();
                
                
                if(img_width > {{ crop_image_area_size }} || img_height > {{ crop_image_area_size }}) {
                    if(img_width >= img_height) {
                        $(this).css('width', "{{ crop_image_area_size }}px");
                    }
                    else {
                        $(this).css('height', "{{ crop_image_area_size }}px");
                    }
                }
                
                img_width = $(this).width();
                img_height = $(this).height();
                
                var sel = {};
                sel['x1'] = Math.round(img_width/2-25 > 0 ? img_width/2-25 : 0),
                sel['y1'] = Math.round(img_height/2-25 > 0 ? img_height/2-25 : 0),
                sel['x2'] = Math.round(img_width/2+25 > img_width ? img_width : img_width/2+25),
                sel['y2'] = Math.round(img_height/2+25 > img_height ? img_height : img_height/2+25),
                sel['width'] = 50;
                
                $(this).imgAreaSelect({
                    handles: true,
                    aspectRatio: "1:1",
                    fadeSpeed: 100,
                    minHeight: 50,
                    minWidth: 50,
                    x1: sel.x1,
                    y1: sel.y1,
                    x2: sel.x2,
                    y2: sel.y2,
                    onSelectChange: updateCoors
                });
                
                updateCoors({'width': img_width}, sel);
            });
        };
        
        function updateCoors(img, selection) {
          $("#uploadAvatarValueX1").val(selection.x1);
          $("#uploadAvatarValueY1").val(selection.y1);
          $("#uploadAvatarValueX2").val(selection.x2);
          $("#uploadAvatarValueY2").val(selection.y2);
          
          {% for p in preview_areas %}
            updatePreview{{ p.size }}(img, selection);
          {% endfor %}
        };
        
        {% for p in preview_areas %}
            function updatePreview{{ p.size }}(img, selection) {
              if(parseInt(selection.width) > 0) {
                var ratiox = {{ p.size }} / selection.width;
                $("#uploadAvatarPreviewArea{{ p.size }} img").css({
                  width: Math.round(ratiox * img.width) + 'px',
                  marginLeft: '-' + Math.round(ratiox * selection.x1) + 'px',
                  marginTop: '-' + Math.round(ratiox * selection.y1) + 'px'
                });
              }
            };
        {% endfor %}
        
        function crop_avatar_success(msg) {
            $('#uploadAvatarCropResult').hide().text(msg).show(200);
        };
    </script>
    
    <form id="uploadAvatarCropForm" action="{% url 'avatar:uploadavatar_crop' %}" method="post" target="uploadAvatarIframe" style="display: none;">
        {% csrf_token %}
        <input id="uploadAvatarValueX1" type="text" name="x1"/>
        <input id="uploadAvatarValueY1" type="text" name="y1"/>
        <input id="uploadAvatarValueX2" type="text" name="x2"/>
        <input id="uploadAvatarValueY2" type="text" name="y2"/>
    </form>
    
    
    
    <div id="uploadAvatarUploadArea">
        <form id="uploadAvatarForm" action="{% url 'avatar:uploadavatar_upload' %}" method="post" target="uploadAvatarIframe" enctype="multipart/form-data">
            {% csrf_token %}
            <div id="uploadAvatarBtnLayout">
                <button>{{ CHOOSE_IMAGE }}</button>
                <input type="file" id="uploadAvatarInputFile" name="uploadavatarfile" />
            </div>
        </form>
    </div>
    <iframe id="uploadAvatarIframe" name="uploadAvatarIframe" style="display: none;"></iframe>
    
    <div id="uploadAvatarSelectArea"></div>
    <div id="uploadAvatarPreviewArea">
        {% for p in preview_areas %}
        <p>{{ p.text }}</p>
        <div id="uploadAvatarPreviewArea{{ p.size }}"></div>
        {% endfor %}
    </div>
    
    <div style="clear: both;"></div>
    
    <div id="uploadAvatarBtns">
        <button id="uploadAvatarCropSubmit" disabled="disabled">{{ CROP_IMAGE }}</button>
    </div>
    
    <div id="uploadAvatarCropResult" style="display: none;"></div>
</div>